# Generated by Django 5.0.1 on 2025-11-12 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("contact_info", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="converters__name_b36b8b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CatalyticConverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executive_order",
                    models.CharField(
                        db_index=True,
                        help_text="CARB Executive Order number",
                        max_length=50,
                    ),
                ),
                (
                    "series_model",
                    models.CharField(
                        blank=True,
                        help_text="Series/Model number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "model_year_start",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "model_year_end",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "make",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Vehicle make (e.g., Honda, Toyota)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Vehicle model", max_length=100, null=True
                    ),
                ),
                (
                    "vehicle_class",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle class (e.g., PC, LDT)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "engine_size",
                    models.CharField(
                        blank=True,
                        help_text="Engine displacement",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "test_group",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "cert_level",
                    models.CharField(
                        blank=True,
                        help_text="Certification level",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        blank=True,
                        help_text="Application type (e.g., Direct-Fit, Universal)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "converter_location",
                    models.CharField(
                        blank=True,
                        help_text="Location on vehicle (e.g., Front, Rear, Manifold)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "converter_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of converter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, help_text="Number of converters", null=True
                    ),
                ),
                (
                    "eo_date",
                    models.DateField(
                        blank=True, help_text="Executive Order date", null=True
                    ),
                ),
                (
                    "last_scraped",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last time this record was updated from CARB",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="converters",
                        to="converters.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalytic Converter",
                "verbose_name_plural": "Catalytic Converters",
                "ordering": ["-eo_date", "make", "model_year_start"],
                "indexes": [
                    models.Index(
                        fields=["executive_order"],
                        name="converters__executi_0b7d4e_idx",
                    ),
                    models.Index(
                        fields=["make", "model_year_start"],
                        name="converters__make_b2124b_idx",
                    ),
                    models.Index(
                        fields=["test_group"], name="converters__test_gr_43bf56_idx"
                    ),
                    models.Index(
                        fields=["eo_date"], name="converters__eo_date_ea1f42_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="converters__is_acti_075696_idx"
                    ),
                ],
            },
        ),
    ]
