# Generated by Django 5.0.1 on 2025-11-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalyticconverter",
            name="part_number",
            field=models.CharField(
                blank=True,
                help_text="Manufacturer part number",
                max_length=255,
                null=True,
            ),
        ),
    ]
