# Generated by Django 4.2.16 on 2025-11-13 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("converters", "0002_catalyticconverter_part_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary that appears in the preview section"
                    ),
                ),
                ("content", models.TextField(help_text="Full blog content")),
                (
                    "hero_image",
                    models.ImageField(
                        help_text="Preview image shown on the homepage",
                        upload_to="blog_images/",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="converters__slug_a339f1_idx"),
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="converters__is_publ_405d4e_idx",
                    ),
                ],
            },
        ),
    ]
