# Generated by Django 5.0.1 on 2025-11-13 19:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("converters", "0003_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="excerpt",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(help_text="Full blog content"),
        ),
    ]
