# Generated by Django 4.2.26 on 2025-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converters", "0004_remove_blogpost_excerpt_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ["name"],
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
            },
        ),
        migrations.CreateModel(
            name="ScraperRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "scraper_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Worker"),
                            ("parallel", "Parallel Workers"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("headless", models.BooleanField(default=True)),
                ("pages_per_eo", models.IntegerField(default=5)),
                ("test_mode", models.BooleanField(default=False)),
                (
                    "num_workers",
                    models.IntegerField(
                        default=1,
                        help_text="Number of parallel workers (for parallel scraper)",
                    ),
                ),
                (
                    "eo_numbers_to_process",
                    models.JSONField(
                        default=list, help_text="List of EO numbers to scrape"
                    ),
                ),
                (
                    "eo_numbers_processed",
                    models.JSONField(
                        default=list,
                        help_text="List of EO numbers that have been processed",
                    ),
                ),
                (
                    "eo_numbers_failed",
                    models.JSONField(
                        default=list, help_text="List of EO numbers that failed"
                    ),
                ),
                ("total_eo_count", models.IntegerField(default=0)),
                ("processed_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("no_results_count", models.IntegerField(default=0)),
                ("partial_count", models.IntegerField(default=0)),
                (
                    "worker_task_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of worker task IDs for parallel scraping",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stop_requested", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Scraper Run",
                "verbose_name_plural": "Scraper Runs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="converters__task_id_177ede_idx"
                    ),
                    models.Index(
                        fields=["status"], name="converters__status_ee6050_idx"
                    ),
                    models.Index(
                        fields=["stop_requested"], name="converters__stop_re_95423e_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="converters__started_51ea39_idx"
                    ),
                ],
            },
        ),
    ]
