# Generated by Django 4.2.26 on 2025-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "converters",
            "0005_alter_blogpost_options_alter_manufacturer_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperrun",
            name="current_eo_number",
            field=models.CharField(
                blank=True,
                help_text="Currently processing EO number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="current_page_number",
            field=models.IntegerField(
                default=1, help_text="Current page number being scraped within the EO"
            ),
        ),
        migrations.AlterField(
            model_name="scraperrun",
            name="pages_per_eo",
            field=models.IntegerField(
                default=999,
                help_text="Maximum pages to scrape per EO (999 = process all pages)",
            ),
        ),
    ]
