# Generated by Django 4.2.26 on 2025-12-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converters", "0006_scraperrun_current_eo_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperrun",
            name="current_retry_pass",
            field=models.IntegerField(
                default=1,
                help_text="Current retry pass number (1 = initial, 2+ = retry passes)",
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="engine_used",
            field=models.CharField(
                choices=[("selenium", "Selenium"), ("playwright", "Playwright")],
                default="playwright",
                help_text="Scraper engine used for this run",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="eo_failure_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed failure information per EO number",
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="eo_retry_queue",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Queue of failed EOs to retry in next pass",
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="max_retry_passes",
            field=models.IntegerField(
                default=3, help_text="Maximum number of retry passes for failed EOs"
            ),
        ),
    ]
