# Generated by Django 4.2.26 on 2025-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converters", "0006_scraperrun_current_eo_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EOProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eo_number", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "last_page",
                    models.IntegerField(
                        default=0,
                        help_text="Last successfully scraped page for this EO",
                    ),
                ),
                ("expected_pages", models.IntegerField(blank=True, null=True)),
                ("expected_rows", models.IntegerField(blank=True, null=True)),
                ("scraped_rows", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "EO Progress",
                "verbose_name_plural": "EO Progress Records",
                "ordering": ["eo_number"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="converters__status_7f03d2_idx"
                    ),
                    models.Index(
                        fields=["eo_number", "status"],
                        name="converters__eo_numb_bf9958_idx",
                    ),
                ],
            },
        ),
    ]
