"""
Bulk import catalytic converter data from a CSV file.

The CSV must include the columns generated by the admin export:
executive_order, series_model, make, model, model_year_start, model_year_end,
vehicle_class, engine_size, test_group, cert_level, application_type,
converter_location, converter_type, quantity, eo_date, manufacturer,
product_name, part_number, notes.
"""

import csv
import os
from datetime import datetime

from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from converters.models import CatalyticConverter, Manufacturer


class Command(BaseCommand):
    help = "Import catalytic converters from a CSV file (streamed in batches)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--path",
            required=True,
            help="Path to the CSV file (e.g. ~/Downloads/catalytic_converters_export copy.csv)",
        )
        parser.add_argument(
            "--batch-size",
            type=int,
            default=5000,
            help="Number of rows per bulk insert (default: 5000)",
        )

    def handle(self, *args, **options):
        path = os.path.expanduser(options["path"])
        batch_size = options["batch_size"]

        if not os.path.exists(path):
            raise CommandError(f"File not found: {path}")

        required_headers = {
            "executive_order",
            "series_model",
            "make",
            "model",
            "model_year_start",
            "model_year_end",
            "vehicle_class",
            "engine_size",
            "test_group",
            "cert_level",
            "application_type",
            "converter_location",
            "converter_type",
            "quantity",
            "eo_date",
            "manufacturer",
            "product_name",
            "part_number",
            "notes",
        }

        self.stdout.write(f"Opening {path}")

        with open(path, newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)

            missing = required_headers - set(reader.fieldnames or [])
            if missing:
                raise CommandError(f"Missing required columns: {', '.join(sorted(missing))}")

            # Cache manufacturers we already have in the DB to avoid repeated lookups
            manufacturer_cache = {
                m.name.lower(): m for m in Manufacturer.objects.all()
            }

            created_manufacturers = 0
            created_converters = 0
            skipped_rows = 0
            batch = []

            def parse_int(value):
                if value is None:
                    return None
                cleaned = str(value).strip()
                if not cleaned or cleaned.lower() in {"nan", "none"}:
                    return None
                try:
                    return int(cleaned)
                except ValueError:
                    return None

            def parse_date(value):
                if value is None:
                    return None
                cleaned = str(value).strip()
                if not cleaned:
                    return None
                try:
                    return datetime.strptime(cleaned, "%Y-%m-%d").date()
                except ValueError:
                    return None

            for idx, row in enumerate(reader, start=2):  # start=2 to match CSV line numbers
                try:
                    manufacturer_name = (row.get("manufacturer") or "").strip()
                    if not manufacturer_name:
                        skipped_rows += 1
                        continue

                    manufacturer_key = manufacturer_name.lower()
                    manufacturer = manufacturer_cache.get(manufacturer_key)
                    if manufacturer is None:
                        manufacturer = Manufacturer.objects.create(
                            name=manufacturer_name, contact_info=""
                        )
                        manufacturer_cache[manufacturer_key] = manufacturer
                        created_manufacturers += 1

                    executive_order = (row.get("executive_order") or "").strip()
                    if not executive_order:
                        skipped_rows += 1
                        continue

                    converter = CatalyticConverter(
                        manufacturer=manufacturer,
                        executive_order=executive_order,
                        series_model=(row.get("series_model") or "").strip() or None,
                        part_number=(row.get("part_number") or "").strip() or None,
                        product_name=(row.get("product_name") or "").strip() or None,
                        model_year_start=parse_int(row.get("model_year_start")),
                        model_year_end=parse_int(row.get("model_year_end")),
                        make=(row.get("make") or "").strip() or None,
                        model=(row.get("model") or "").strip() or None,
                        vehicle_class=(row.get("vehicle_class") or "").strip() or None,
                        engine_size=(row.get("engine_size") or "").strip() or None,
                        test_group=(row.get("test_group") or "").strip() or None,
                        cert_level=(row.get("cert_level") or "").strip() or None,
                        application_type=(row.get("application_type") or "").strip() or None,
                        converter_location=(row.get("converter_location") or "").strip()
                        or None,
                        converter_type=(row.get("converter_type") or "").strip() or None,
                        quantity=parse_int(row.get("quantity")) or 1,
                        eo_date=parse_date(row.get("eo_date")),
                        notes=(row.get("notes") or "").strip() or None,
                        is_active=True,
                        last_scraped=timezone.now(),
                    )

                    batch.append(converter)

                    if len(batch) >= batch_size:
                        CatalyticConverter.objects.bulk_create(batch, batch_size=batch_size)
                        created_converters += len(batch)
                        batch.clear()

                except Exception as exc:  # noqa: BLE001
                    skipped_rows += 1
                    self.stderr.write(f"Row {idx}: {exc}")

            if batch:
                CatalyticConverter.objects.bulk_create(batch, batch_size=batch_size)
                created_converters += len(batch)

        self.stdout.write(
            self.style.SUCCESS(
                f"Import completed. Converters created: {created_converters}, "
                f"Manufacturers created: {created_manufacturers}, "
                f"Rows skipped: {skipped_rows}"
            )
        )
